### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by shumlak** [UW-Computational-Plasma-Group/warpii#52]
Some of the output from "make build":
[ 40%] Building CXX object src/CMakeFiles/libwarpii.dir/dgsem/nodal_dg_discretization.cc.o
In file included from /Users/shumlak/WARPX/code/warpii/src/five_moment/flux_operator.cc:1:
In file included from /Users/shumlak/WARPX/code/warpii/src/five_moment/flux_operator.h:2:
In file included from /Users/shumlak/WARPX/code/warpii/src/five_moment/fluid_flux_es_dgsem_operator.h:3:
In file included from /Users/shumlak/WARPX/warpiisoft/deps/dealii/dealii-9.5.1-RelWithDebInfo/include/deal.II/bundled/boost/variant/variant.hpp:21:
In file included from /Users/shumlak/WARPX/warpiisoft/deps/dealii/dealii-9.5.1-RelWithDebInfo/include/deal.II/bundled/boost/type_index.hpp:29:
In file included from /Users/shumlak/WARPX/warpiisoft/deps/dealii/dealii-9.5.1-RelWithDebInfo/include/deal.II/bundled/boost/type_index/stl_type_index.hpp:47:
/Users/shumlak/WARPX/warpiisoft/deps/dealii/dealii-9.5.1-RelWithDebInfo/include/deal.II/bundled/boost/container_hash/hash.hpp:130:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
        struct hash_base : std::unary_function<T, std::size_t> {};
                           ~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^

**Comment by johnbcoughlin** [comment]
@shumlak I ran into this as well, pretty frustrating. You should `brew install boost` and then rebuild deal.II. I will add this to the install instructions.

**Comment by johnbcoughlin** [comment]
Should be clearer now with #54
